# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SessionFinder < Formula
  desc "Search local AI sessions from multiple tools"
  homepage "https://github.com/BayInl/session-finder"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BayInl/session-finder/releases/download/v0.2.0/session-finder_0.2.0_darwin_amd64.tar.gz"
      sha256 "7f26c5755ee2e472d02681355e822725d1c81408b99427483a67fa228b3ee002"

      define_method(:install) do
        bin.install "session-finder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BayInl/session-finder/releases/download/v0.2.0/session-finder_0.2.0_darwin_arm64.tar.gz"
      sha256 "02518abf6b58b94882cfc5d49b508a3cb766c46517bffa27b5e0bf55c13beb8a"

      define_method(:install) do
        bin.install "session-finder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/BayInl/session-finder/releases/download/v0.2.0/session-finder_0.2.0_linux_amd64.tar.gz"
      sha256 "f7dee044d826a98fb21914bd21d753e9cb04fbc8426399bd2978ba1c66feded0"
      define_method(:install) do
        bin.install "session-finder"
      end
    end
  end

  test do
    system "#{bin}/session-finder", "--help"
  end
end
