# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sfind < Formula
  desc "Search local AI coding sessions from multiple tools"
  homepage "https://github.com/BayInl/session-finder"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BayInl/session-finder/releases/download/v0.4.1/session-finder_0.4.1_darwin_amd64.tar.gz"
      sha256 "42cfbc0eea2d013a0f00074d62d264e6a749e623940eb6f5604fd83d5746dc60"

      define_method(:install) do
        bin.install "sfind"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BayInl/session-finder/releases/download/v0.4.1/session-finder_0.4.1_darwin_arm64.tar.gz"
      sha256 "d928a85de7970313cf920fd37e7384c7b5c7eed2eda111d5a92abd1243fb3b38"

      define_method(:install) do
        bin.install "sfind"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/BayInl/session-finder/releases/download/v0.4.1/session-finder_0.4.1_linux_amd64.tar.gz"
      sha256 "dcca6c09b0ffa818cd81fe43161a576754b41a571f49b9281a3a58ef1041444a"
      define_method(:install) do
        bin.install "sfind"
      end
    end
  end

  test do
    system "#{bin}/sfind", "--help"
  end
end
